on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to test the action
    steps:
      - name: Tester
        id: test
        uses: nuvla/nuvla-create-nuvlabox-action@v0
        with:
          api-key: 'mykey'
          api-secret: 'mysecret'
          vpn-server-id: 'vpnid'
          nuvlabox-release: 'nuvlabox-release/uuid'
          name: "name"
      # Use the output 
      - name: Get the output 
        run: echo "The output was ${{ steps.test.outputs.NUVLABOX_UUID }}"
